# Generated by Django 4.2.1 on 2023-05-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Список товаров'},
        ),
    ]
