# Generated by Django 4.2.1 on 2023-05-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_tea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={'verbose_name': 'Чай', 'verbose_name_plural': 'Список чая'},
        ),
    ]
