# Generated by Django 4.2.1 on 2023-05-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_tea_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=50, verbose_name='Товар')),
                ('customer_fname', models.CharField(max_length=50, verbose_name='Имя')),
                ('customer_lname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('paymentmethod', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Покупки',
                'verbose_name_plural': 'Покупка',
            },
        ),
    ]
